Gui and bisection zero position find alghoritm
kambed/Numerki pull request #3
Opened 2022-03-05 19:53 UTC by RadekBucki

2022-03-08 18:47 UTC, kambed requested changes

2022-03-08 18:47 UTC, kambed commented on src/main/java/pl/numerki/backend/Bisection.java
> +    ) throws Exception {
should be BisectionException

2022-03-08 18:47 UTC, kambed commented on src/main/java/pl/numerki/frontend/MainFormController.java
> +    public void squareFunctionChosen(ActionEvent actionEvent) {
do function with 3 bool args to set visibility of a b c in *Chosen functions

2022-03-08 18:47 UTC, kambed commented on src/main/java/pl/numerki/frontend/MainFormController.java
> +    public void showIterations(ActionEvent actionEvent) {
do function with 2 bool values for precision and iterations as well

2022-03-08 18:47 UTC, kambed commented on src/main/java/pl/numerki/frontend/MainFormController.java
> +        return switch (chosenFunction) {
NO default value compilation error

2022-03-08 18:47 UTC, kambed commented on src/main/java/pl/numerki/frontend/MainFormController.java
> +            AlertBox.alertShow(
Shouldn't there be some error or sth like that?

2022-03-08 18:47 UTC, kambed commented on src/main/java/pl/numerki/backend/Bisection.java
> +    ) throws Exception {
same thing Bisextion excpetion

2022-03-08 18:47 UTC, kambed commented on src/main/java/pl/numerki/backend/Bisection.java
> +    ) throws Exception {
same thing Bisextion excpetion

2022-03-08 18:47 UTC, kambed commented on src/main/java/pl/numerki/backend/SecantMethod.java
> +    ) throws Exception {
exception

2022-03-08 18:47 UTC, kambed commented on src/main/java/pl/numerki/backend/SecantMethod.java
> +    ) throws Exception {
exception

2022-03-08 18:47 UTC, kambed commented on src/main/java/pl/numerki/backend/Bisection.java
> +            if (function.apply(leftEndOfCompartment) * function.apply(compartmentMiddle) < 0) {
You can extract this to function and get rid of else

2022-03-08 18:47 UTC, kambed commented on src/main/java/pl/numerki/backend/Bisection.java
> +            if (function.apply(leftEndOfCompartment) * function.apply(compartmentMiddle) < 0) {
You can extract this to function and get rid of else

2022-03-08 20:11 UTC, RadekBucki commented on src/main/java/pl/numerki/frontend/MainFormController.java
> +            AlertBox.alertShow(
the error is below :), it adjust to error for example only one of zero position calculation method
```
                        "Metoda bisekcji: " + (bisectionException ? "NanN" : resultBisection) +
                        "\nMetoda siecznych: " + (secantException ? "NaN" : resultSecant),
```

2022-03-09 10:46 UTC, kambed approved these changes

2022-03-09 10:46 UTC, merged